name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: committer
        env:
          AUTHOR: ${{ github.event.commits[0].author.name }}
        run: echo "$AUTHOR"
      - name: committer
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages skip
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ', ') }}    
        if: contains(env.COMMIT_MESSAGES, '#skip')
        run: echo "$COMMIT_MESSAGES"
        # run: echo skip
      - name: commit messages noskip
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ', ') }}    
        if: |
          !contains(env.COMMIT_MESSAGES, '#skip')
        run: echo "$COMMIT_MESSAGES"
        # run: echo noskip
